# Generated by Django 2.1.1 on 2018-09-25 09:46

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Не более 120 символов', max_length=120, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(help_text='Не более 120 символов', max_length=120, unique=True, verbose_name='URL')),
                ('text', tinymce.models.HTMLField(verbose_name='Текст')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активировать')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Статичная страница',
                'verbose_name_plural': 'Статичные страницы',
            },
        ),
    ]
