# Generated by Django 2.1.1 on 2018-09-14 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='usr',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
