# Generated by Django 2.1.1 on 2018-09-06 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributesBooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Не более 120 символов', max_length=120, verbose_name='Название аттрибута')),
                ('value', models.CharField(blank=True, help_text='Не более 128 символов', max_length=128, null=True, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Атрибут книги',
                'verbose_name_plural': 'Атрибуты книг',
            },
        ),
        migrations.CreateModel(
            name='AuthorBooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Не более 120 символов', max_length=120, verbose_name='Имя')),
                ('secondary_name', models.CharField(blank=True, help_text='Не более 120 символов', max_length=120, null=True, verbose_name='Отчество')),
                ('last_name', models.CharField(help_text='Не более 120 символов', max_length=120, verbose_name='Фамилия')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активировать')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete='SET_NULL', to=settings.AUTH_USER_MODEL, verbose_name='Продавец')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Не более 120 символов', max_length=120, verbose_name='Название')),
                ('description', tinymce.models.HTMLField(verbose_name='Описание')),
                ('date', models.CharField(blank=True, help_text='Не более 4 символов', max_length=4, verbose_name='Дата выхода')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Цена за единицу товара', max_digits=10, verbose_name='Цена')),
                ('discount', models.IntegerField(blank=True, default=0, help_text='В процентах', null=True, verbose_name='Скидка')),
                ('price_discount', models.DecimalField(decimal_places=2, default=0.0, help_text='Заполняется автоматически', max_digits=10, verbose_name='Цена c учётом скидки')),
                ('counter', models.IntegerField(blank=True, default=0, help_text='В наличии', null=True, verbose_name='Количество')),
                ('preview', models.ImageField(upload_to='catalogApp/preview/', verbose_name='Превью')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активировать')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('attributes', models.ManyToManyField(blank=True, help_text='Зажмите shift, чтобы выбрать несколько вариантов', related_name='rel_attrib', to='catalogApp.AttributesBooks', verbose_name='Аттрибуты')),
                ('author', models.ManyToManyField(blank=True, help_text='Зажмите shift, чтобы выбрать несколько вариантов', related_name='rel_author', to='catalogApp.AuthorBooks', verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
        migrations.CreateModel(
            name='CommentsBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', tinymce.models.HTMLField(verbose_name='Отзыв')),
                ('rate', models.IntegerField(blank=True, default=10, help_text='От 1 до 10', verbose_name='Рейтинг')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активировать')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogApp.Books', verbose_name='Книга')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete='SET_NULL', to=settings.AUTH_USER_MODEL, verbose_name='Опубликовал')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Не более 120 символов', max_length=120, verbose_name='Название')),
                ('slug', models.SlugField(help_text='Не более 120 символов', max_length=120, verbose_name='Транслит')),
                ('rune', models.CharField(blank=True, help_text='Не более 12 символов', max_length=12, verbose_name='Символ')),
                ('quota', models.DecimalField(decimal_places=2, default=0.0, help_text='Цена относительно доллара', max_digits=10, verbose_name='Курс')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активировать')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
            },
        ),
        migrations.CreateModel(
            name='GenreBooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Не более 120 символов', max_length=120, unique=True, verbose_name='Название жанра')),
                ('slug', models.SlugField(blank=True, help_text='Не более 128 символов', max_length=128, null=True, unique=True, verbose_name='Ссылка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активировать')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete='SET_NULL', to=settings.AUTH_USER_MODEL, verbose_name='Продавец')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='PublicHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Не более 120 символов', max_length=120, unique=True, verbose_name='Название издательства')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активировать')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete='SET_NULL', to=settings.AUTH_USER_MODEL, verbose_name='Продавец')),
            ],
            options={
                'verbose_name': 'Издательство',
                'verbose_name_plural': 'Издательства',
            },
        ),
        migrations.CreateModel(
            name='TagsBooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Не более 120 символов', max_length=120, unique=True, verbose_name='Название метки')),
                ('slug', models.SlugField(blank=True, help_text='Не более 128 символов', max_length=128, null=True, unique=True, verbose_name='Ссылка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активировать')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete='SET_NULL', to=settings.AUTH_USER_MODEL, verbose_name='Продавец')),
            ],
            options={
                'verbose_name': 'Метка',
                'verbose_name_plural': 'Метки',
            },
        ),
        migrations.AddField(
            model_name='books',
            name='genre',
            field=models.ManyToManyField(blank=True, help_text='Зажмите shift, чтобы выбрать несколько вариантов', related_name='rel_genre', to='catalogApp.GenreBooks', verbose_name='Жанр'),
        ),
        migrations.AddField(
            model_name='books',
            name='phouse',
            field=models.ManyToManyField(blank=True, help_text='Зажмите shift, чтобы выбрать несколько вариантов', related_name='rel_phouse', to='catalogApp.PublicHouse', verbose_name='Издательство'),
        ),
        migrations.AddField(
            model_name='books',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Зажмите shift, чтобы выбрать несколько вариантов', related_name='rel_tag', to='catalogApp.TagsBooks', verbose_name='Метка'),
        ),
        migrations.AddField(
            model_name='books',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete='SET_NULL', to=settings.AUTH_USER_MODEL, verbose_name='Опубликовал'),
        ),
    ]
