# Generated by Django 2.1.1 on 2018-09-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0003_auto_20180916_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Максимальный размер 100х100', null=True, upload_to='avatar/', verbose_name='Аватарка'),
        ),
    ]
