# Generated by Django 2.1.1 on 2018-09-06 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, null=True, verbose_name='Имя получателя')),
                ('country', models.CharField(max_length=120, null=True, verbose_name='Страна/Регион')),
                ('street', models.CharField(max_length=120, null=True, verbose_name='Улица, дом, квартира')),
                ('apt', models.CharField(blank=True, help_text='При необходимости', max_length=120, null=True, verbose_name='Квартира, блок')),
                ('region', models.CharField(max_length=120, null=True, verbose_name='Край/Область/Регион')),
                ('city', models.CharField(max_length=120, null=True, verbose_name='Город')),
                ('postcode', models.PositiveIntegerField(null=True, verbose_name='Почтовый индекс')),
                ('phone', models.CharField(max_length=25, null=True, verbose_name='Номер телефона')),
                ('is_active', models.BooleanField(default=True, help_text='Видно пользователям, только если активно', verbose_name='Активно')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderObjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(help_text='ID объекта указанной модели', verbose_name='ID объекта')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Цена за единицу товара', max_digits=10, verbose_name='Цена')),
                ('count', models.PositiveIntegerField(default=1, help_text='Не менее одного', verbose_name='Количество')),
                ('is_active', models.BooleanField(default=True, help_text='Видно пользователям, только если активно', verbose_name='Активно')),
                ('content_type', models.ForeignKey(help_text='Выберите модель', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='Модель')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderApp.Order', verbose_name='Заказ')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete='SET_NULL', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Товар заказа',
                'verbose_name_plural': 'Товар Заказов',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Не более 30 символов.', max_length=30, verbose_name='Название')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Статус заказа',
                'verbose_name_plural': 'Статусы заказов',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(on_delete='SET_NULL', to='orderApp.Status', verbose_name='Статус заказа'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete='SET_NULL', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
    ]
