# Generated by Django 2.1.1 on 2018-09-15 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orderApp', '0002_auto_20180914_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderobjects',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderobj', to='orderApp.Order', verbose_name='Заказ'),
        ),
    ]
