# Generated by Django 2.1.1 on 2018-09-16 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderApp', '0003_auto_20180915_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete='SET_NULL', to='orderApp.Status', verbose_name='Статус заказа'),
        ),
    ]
